"""
constants.py â€” Simple mode

Key idea:
- Internal cutouts (slots, holes, pockets) end up LARGER by ~kerf.
  => draw_size = target_physical - kerf
- External parts (tabs, outer sizes) end up SMALLER by ~kerf.
  => draw_size = target_physical + kerf

You will calibrate:
- KERF_MM (if you want)
- NUT_POCKET_CLEARANCE_MM (to prevent jiggle)
- DIVIDER_SLOT_CLEARANCE_MM (for smooth slip fit)
- SCREW_HOLE_DIAMETER_MM (clearance for 2-56 screw)
"""

INCH_TO_MM = 25.4

# Fixed material
T_MM = 3.0

# Default kerf (you will calibrate)
KERF_MM_DEFAULT = 0.10

# Sheet size (one sheet per box)
SHEET_W_MM = 12.0 * INCH_TO_MM
SHEET_H_MM = 18.0 * INCH_TO_MM

# Packing gap between parts on sheet
PART_GAP_MM = 2.0

# Safety margins
MIN_EDGE_MARGIN_MM = max(2 * T_MM, 6.0)

# Engraving safe margin inside each wall
ENGRAVE_MARGIN_MM = max(2 * T_MM, 6.0)

# Divider rules
DIVIDER_MIN_GAP_MM = max(2 * T_MM, 6.0)

# --------------------------
# Fit tuning (PHYSICAL targets)
# --------------------------
# Divider slots: slip fit for 3mm divider. Start at +0.08mm and tune from test strip.
DIVIDER_SLOT_CLEARANCE_MM = 0.08

# Nut pocket: should NOT spin; should have minimal wiggle.
# Start at +0.05mm and tune from test strip.
NUT_POCKET_CLEARANCE_MM = 0.05

# Screw hole diameter (clearance). Start at 2.50mm and tune if needed.
SCREW_HOLE_DIAMETER_MM = 2.50

# --------------------------
# Hardware (square nut) saved specs
# --------------------------
NUT_WIDTH_IN = 0.188
NUT_WIDTH_MM = NUT_WIDTH_IN * INCH_TO_MM

# --------------------------
# Helper conversions for kerf-aware drawing
# --------------------------
def internal_cut_draw_dim(target_physical_mm: float, kerf_mm: float) -> float:
    """For holes/slots/pockets (internal voids)."""
    return target_physical_mm - kerf_mm

def external_cut_draw_dim(target_physical_mm: float, kerf_mm: float) -> float:
    """For external features (tabs, tongues) if you add them later."""
    return target_physical_mm + kerf_mm

def divider_slot_target_physical(kerf_mm: float) -> float:
    """Desired physical slot width for a 3mm divider slip fit."""
    return T_MM + DIVIDER_SLOT_CLEARANCE_MM

def divider_slot_draw_w(kerf_mm: float) -> float:
    return internal_cut_draw_dim(divider_slot_target_physical(kerf_mm), kerf_mm)

def nut_pocket_target_physical() -> float:
    """Desired physical pocket width (square)."""
    return NUT_WIDTH_MM + NUT_POCKET_CLEARANCE_MM

def nut_pocket_draw_w(kerf_mm: float) -> float:
    return internal_cut_draw_dim(nut_pocket_target_physical(), kerf_mm)

def screw_hole_draw_d(kerf_mm: float) -> float:
    return internal_cut_draw_dim(SCREW_HOLE_DIAMETER_MM, kerf_mm)

# Divider slot vertical geometry (standardized)
DIVIDER_SLOT_TOP_CAP_MM = MIN_EDGE_MARGIN_MM
DIVIDER_SLOT_BOTTOM_MARGIN_MM = MIN_EDGE_MARGIN_MM

# Engraving defaults
TEXT_FONT_FAMILY = "Arial"
TEXT_FONT_SIZE_MM = 6.0
TEXT_ANCHOR = "middle"
